export const JURISDICTION_PROFILES = {
  loving_county_tx: {
    name: 'Loving County, Texas',
    population: 64,
    lastCodeUpdate: 1987,
    peakDemandMW: 8,
    aquiferRechargeRateGPD: 2_400_000,
    applicableCodes: [
      {
        code: 'LCC §4.02',
        title: 'Building Permits — General Requirements',
        description: 'All structures require building permit from County Judge. Applies to residential, commercial, and agricultural structures. No provisions for industrial-scale facilities.',
        year: 1987,
      },
      {
        code: 'LCC §6.01',
        title: 'Water Well Permits',
        description: 'All new water wells require county permit. Maximum permitted withdrawal: 10,000 GPD per parcel without Edwards Aquifer Authority review. No provisions for industrial water usage.',
        year: 1987,
      },
      {
        code: 'LCC §3.15',
        title: 'Road Access and Driveway Permits',
        description: 'All new access points to county roads require permit. Road impact fees: $500 per residential, $2,000 per commercial. No heavy vehicle or construction traffic provisions.',
        year: 1987,
      },
      {
        code: 'LCC §5.03',
        title: 'Sign Regulations',
        description: 'Maximum sign height: 20 feet. Maximum illuminated sign area: 32 sq ft. No digital/LED sign provisions.',
        year: 1987,
      },
      {
        code: 'LCC §2.08',
        title: 'Land Use Classifications',
        description: 'Three zones: Residential, Commercial, Agricultural/Ranch. No industrial zone. No technology/data center classification.',
        year: 1987,
      },
    ],
    classificationGaps: [
      'No "data center" or "technology facility" land use classification exists',
      'No utility-scale battery storage classification — not anticipated in 1987 code',
      'No EV charging infrastructure provisions — technology did not exist',
      'No electrical load thresholds for commercial permits (current code assumes <100kW)',
      'No industrial water usage category — code only addresses residential/agricultural wells',
      'No hazardous materials storage ordinance for lithium-ion batteries',
      'No noise ordinance applicable to industrial cooling systems',
      'No fire code provisions for lithium-ion battery installations (NFPA 855 not adopted)',
      'No construction traffic management requirements for projects >$1M',
      'No environmental review trigger thresholds (no local NEPA equivalent)',
    ],
  },
  austin_tx: {
    name: 'Austin, Texas',
    population: 979_263,
    lastCodeUpdate: 2024,
    peakDemandMW: 3_200,
    aquiferRechargeRateGPD: 45_000_000,
    applicableCodes: [],
    classificationGaps: [],
  },
  travis_county_tx: {
    name: 'Travis County, Texas',
    population: 1_290_000,
    lastCodeUpdate: 2023,
    peakDemandMW: 4_500,
    aquiferRechargeRateGPD: 60_000_000,
    applicableCodes: [],
    classificationGaps: [],
  },
}
