export const PERMIT_CHECKLISTS = {
  data_center: [
    'Site plan with building footprints, setbacks, and lot coverage',
    'Electrical load analysis and utility interconnection agreement',
    'Water supply plan with source identification and usage projections',
    'Wastewater treatment and discharge plan',
    'Cooling system specifications and thermal discharge analysis',
    'Fire suppression system design (NFPA 75/76 compliance)',
    'Backup generator specifications and fuel storage plan',
    'Environmental impact assessment or categorical exclusion documentation',
    'Traffic impact analysis for construction and operations phases',
    'Noise study with boundary-line projections',
    'Stormwater management plan with detention calculations',
    'Structural engineering report for server floor loading',
    'Security plan and perimeter fencing details',
    'Decommissioning plan with financial assurance/bonding',
  ],
  battery_storage: [
    'Battery chemistry and cell specifications',
    'Thermal management system design',
    'Fire suppression plan (NFPA 855 compliance)',
    'Thermal runaway containment and deflagration venting design',
    'Hazardous materials inventory and emergency response plan',
    'Electrical interconnection study and utility agreement',
    'Site grading and stormwater plan',
    'Decommissioning and recycling plan with cost estimates',
    'Emergency access roads and fire department consultation',
    'Environmental containment for electrolyte leakage',
    'Insurance certificate with pollution liability coverage',
  ],
  ev_charging: [
    'Electrical load study and distribution feeder capacity analysis',
    'Site plan with stall layout, ADA compliance, and traffic flow',
    'Utility interconnection agreement or service upgrade plan',
    'Signage plan with height, illumination, and setback details',
    'Stormwater management for impervious surface additions',
    'Traffic impact analysis for site access and adjacent roadways',
    'Building code compliance for any enclosed structures',
  ],
  building_use_change: [
    'Current and proposed use description with SIC/NAICS codes',
    'Structural analysis for proposed use loading requirements',
    'Electrical service upgrade plan with load calculations',
    'Fire code analysis for new occupancy classification',
    'ADA compliance assessment for public-facing uses',
    'Parking analysis per new use requirements',
    'Hazardous materials disclosure for industrial uses',
    'Water and wastewater capacity analysis for new use',
    'Zoning compliance verification or variance application',
    'Building code occupancy change documentation',
  ],
}
